export const pathtotitle: { [key: string]: string } = {
  "/admin/dashboard": "Dashboard",
  "/admin/interviews": "Lịch phỏng vấn",
  "/admin/reports": "Báo cáo tuyển dụng",
  "/admin/social-insurances": "Tra cứu BHXH",
  "/admin/candidates/create": "Quản lý ứng viên",
  "/admin/candidates/list": "Quản lý ứng viên",
  "/admin/recruiters": "Quản lý nhà tuyển dụng",
  "/admin/recruiters/pending": "Nhà tuyển dụng chờ xác thực",
  "/admin/recruiters/create": "Quản lý nhà tuyển dụng",
  "/admin/jobs": "Tin tuyển dụng",
  "/admin/jobs/create": "Tin tuyển dụng",
  "/admin/jobs/edit/:id": "Tin tuyển dụng",
  "/admin/jobs/pending": "Tin chờ duyệt",
  "/admin/jobs/suggested": "Gợi ý việc làm",
  "/admin/jobs/candidates": "Ứng viên của tin",
  "/admin/candidates/jobs": "Tin tuyển dụng đã ứng tuyển",
  "/admin/interviews/candidate": "Lịch PV theo ứng viên",
  "/admin/requests": "Yêu cầu hỗ trợ",
  "/admin/categories/industries": "Ngành nghề",
  "/admin/categories/skills": "Kỹ năng",
  "/admin/settings": "Cài đặt tài khoản",
  "/candidate/jobs": "Việc làm cho ứng viên",
  "/candidate": "Trang chủ ứng viên",
  "/candidate/jobs/applied": "Việc đã ứng tuyển",
  "/candidate/courses": "Khóa học",
  "/candidate/interviews": "Lịch phỏng vấn",
  "/candidate/profile": "Hồ sơ của tôi",
  "/candidate/support": "Yêu cầu hỗ trợ",
  "/recruiter": "Dashboard",
  "/recruiter/jobs": "Tin tuyển dụng của bạn",
  "/recruiter/jobs/create": "Tin tuyển dụng của bạn",
  "/recruiter/jobs/edit/:id": "Tin tuyển dụng của bạn",
  "/recruiter/jobs/candidates": "Ứng viên cho tin",
  "/recruiter/jobs/suggested-candidates": "Gợi ý ứng viên",
  "/recruiter/interviews": "Lịch phỏng vấn",
  "/recruiter/profile": "Hồ sơ doanh nghiệp",
  "/recruiter/settings": "Cài đặt tài khoản",
  "/recruiter/support": "Yêu cầu hỗ trợ",
  "/center": "Trang chủ",
  "/center/courses": "Khóa học",
  "/center/settings": "Cài đặt tài khoản",
  "/center/support": "Yêu cầu hỗ trợ",
};
